#include <furi.h>
#include <gui/gui.h>
#include <input/input.h>

/* generated by fbt from .png files in images folder */
#include <mode7_demo_icons.h>

int redraw = 0;
int pause = 0;
int grid_scale = 8;
float pos_y = 0;
float speed_y = 50.0f;
float prev_time = 0;

static void draw_callback(Canvas* canvas, void* context)
{
    UNUSED(context);

    // Magical "Mode 7" algorithm
    int width = canvas_width(canvas);
    int height = canvas_height(canvas);
    int half_width = width / 2;
    int half_height = height / 2;
    int grid_size = 8 * grid_scale;
    float inv_grid_size = 1.0f / grid_size;
    float time = ((float)furi_get_tick() / furi_kernel_get_tick_frequency());
    float delta = time - prev_time;
    if (!pause) {
        pos_y += speed_y * delta;
    }
    prev_time = time;
    float inv_height = 1.0f / (float)height;
    for (int x = 0; x < width; ++x) {
        canvas_draw_dot(canvas, x, half_height);
    }
    for (int y = 0; y < height; ++y) {
        if (y > half_height-2 && y < half_height+2) { continue; }

        float z = -0.5f + ((float)y * inv_height);
        float inv_z = 1.0f / z;

        float v = fabsf((float)y * inv_z) + pos_y;

        for (int x = 0; x < width; ++x) {

            float u = (float)(x - half_width) * inv_z;
            if (u < 0.0f) { u = -u + grid_size; }

            int a = (int)(u * inv_grid_size) % 2;
            int b = (int)(v * inv_grid_size) % 2;
            if (a == b) {
                canvas_draw_dot(canvas, x, y);
            }
        }
    }

    redraw = 1;
}

static void input_callback(InputEvent* input_event, void* context)
{
    FuriMessageQueue* event_queue = context;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

int32_t mode7_demo_app(void* p)
{
    UNUSED(p);

    // Initialize event queue
    FuriMessageQueue *event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    if (event_queue == NULL) {
        return 1;
    }

    // Initialize view port
    ViewPort *view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, draw_callback, view_port);
    view_port_input_callback_set(view_port, input_callback, event_queue);

    // Register view port in GUI
    Gui *gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    // Start the event loop
    InputEvent event;
    while (1) {
        // Get event from event queue
        FuriStatus event_status = furi_message_queue_get(event_queue, &event, 100);
        if (event_status == FuriStatusOk) {
            if (event.type == InputTypePress && event.key == InputKeyBack) {
                break;
            }
            if (event.type == InputTypePress && event.key == InputKeyUp) {
                speed_y += 25.0f;
            }
            if (event.type == InputTypePress && event.key == InputKeyDown) {
                speed_y -= 25.0f;
            }
            if (event.type == InputTypePress && event.key == InputKeyLeft) {
                grid_scale -= 1;
                if (grid_scale < 1) { grid_scale = 1; } // min = 1
            }
            if (event.type == InputTypePress && event.key == InputKeyRight) {
                grid_scale += 1;
                if (grid_scale > 8) { grid_scale = 8; } // max = 8
            }
            if (event.type == InputTypePress && event.key == InputKeyOk) {
                pause = !pause;
            }
        } else {
            if (redraw) {
                redraw = 0;
                view_port_update(view_port);
            }
        }
    }

    // Release allocated resources
    furi_message_queue_free(event_queue);
    gui_remove_view_port(gui, view_port);
    furi_record_close(RECORD_GUI);
    view_port_free(view_port);

    return 0;
}